version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - db
  php:
    image: php:fpm
    ports:
      - "9000:9001"
    volumes:
      - ./symfony-doker:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    depends_on:
      - db
    networks:
      - db
      - php
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony-doker:/var/www/symfony:cached
networks:
  db:
  php: